### ISSUE TITLE
Not compatible with HIFI RUSH (microsoft store)

### ISSUE THREAD

**Issue by DDXDB** [AnimatedSwine37/UnrealEssentials#13]
When launched using the Xbox APP:
[2024-10-19 19.11.08 ~ Hi-Fi-RUSH.txt](https://github.com/user-attachments/files/17447060/2024-10-19.19.11.08.Hi-Fi-RUSH.txt)
When launched using the shortcut created by Reloaded-II:
[2024-10-19 19.29.10 ~ Hi-Fi-RUSH.txt](https://github.com/user-attachments/files/17447063/2024-10-19.19.29.10.Hi-Fi-RUSH.txt)

Folder structure:
![屏幕截图 2024-10-20 033716](https://github.com/user-attachments/assets/c52df67b-43b9-4003-b206-8ddab9055e34)

Using this Mods test:
https://www.nexusmods.com/hifirush/mods/14?tab=description

**Comment by AnimatedSwine37** [comment]
That folder structure is a problem. The files need to be in a folder called `UnrealEssentials`. 

In your case all those files would be in `Reloaded-II/Mods/Hibiki.Mods.UnrealEssentials/UnrealEssentials/`. If you want you could put them in a sub folder inside of that `UnrealEssentials` folder and I think it should work too.

There are also errors that are logged only in the one from when you launched the game through the reloaded shortcut. Maybe you just need to always use the xbox app, gamepass is weird sometimes.

**Comment by DDXDB** [comment]
> That folder structure is a problem. The files need to be in a folder called `UnrealEssentials`.
> 
> In your case all those files would be in `Reloaded-II/Mods/Hibiki.Mods.UnrealEssentials/UnrealEssentials/`. If you want you could put them in a sub folder inside of that `UnrealEssentials` folder and I think it should work too.
> 
> There are also errors that are logged only in the one from when you launched the game through the reloaded shortcut. Maybe you just need to always use the xbox app, gamepass is weird sometimes.

The mod can be detected after modifying the path, but the launch game crashes, has been tested with multiple mods

**Comment by AnimatedSwine37** [comment]
Alright, that sucks. It might be something to do with the game pass version of the game but it could also be due to you having some Chinese characters in the path that the files are in.

Utoc Emulator (which Unreal Essentials uses) has had issues in the past where it would crash if the path to any files contained non ASCII characters. I thought they were fixed but maybe not...

Could you try moving your whole Reloaded-II folder to somewhere that only has English/ASCII characters in the path. If that works I can look and probably fix it so you can move stuff back, if not it'd be something with the game.

**Comment by DDXDB** [comment]
> Alright, that sucks. It might be something to do with the game pass version of the game but it could also be due to you having some Chinese characters in the path that the files are in.
> 
> Utoc Emulator (which Unreal Essentials uses) has had issues in the past where it would crash if the path to any files contained non ASCII characters. I thought they were fixed but maybe not...
> 
> Could you try moving your whole Reloaded-II folder to somewhere that only has English/ASCII characters in the path. If that works I can look and probably fix it so you can move stuff back, if not it'd be something with the game.

No, no matter the path, "桌面" translates to desktop, the display is provided by windows, I also moved it to D:\, the problem remains.
![屏幕截图 2024-10-23 221456](https://github.com/user-attachments/assets/46a0b568-dfb3-4341-b0ce-4c3e2da76b5c)

**Comment by DDXDB** [comment]
> Ah ok, I didn't realise windows changed the display like that.
> 
> Would you be able to send me the game's exe? I don't have the microsoft store version of the game and the only thing I can really think to do at this point (without buying it so I can try myself) is to check that the signatures are actually correct for it.
https://1drv.ms/u/s!Akiq9eKkT_m3zQ-3w3etkGpNLNBx?e=8cGzRf

**Comment by TheBestAstroNOT** [comment]
@AnimatedSwine37  Do you want me to test the game's exe. I've seen this issue hasn't had any activity for a while. I do own Hi-fi rush via gamepass.

**Comment by AnimatedSwine37** [comment]
Yeah, that'd be helpful. It has been a while, sorry DDXDB...
Just try it out with the latest version of unreal essentials and see how things go. I think there's a chance that my fix for #14 would've also fixed this.

**Comment by AnimatedSwine37** [comment]
Oh, awesome. I'm glad it works :)
